"""Rename columns from_name  from and unsub_link  unsubscribeLink

Revision ID: cb5af367ab85
Revises: b497be168c9c
Create Date: 2025-05-27 14:41:58.883978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb5af367ab85'
down_revision = 'b497be168c9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('unsubscribeLink', sa.String(length=512), nullable=True))
        batch_op.drop_column('from_name')
        batch_op.drop_column('unsub_link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unsub_link', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('from_name', sa.VARCHAR(length=256), nullable=True))
        batch_op.drop_column('unsubscribeLink')
        batch_op.drop_column('from')

    # ### end Alembic commands ###
